### ISSUE TITLE
Carthage failure

### ISSUE THREAD

**Issue by ghost** [jessesquires/DefaultStringConvertible#4]
## New issue checklist

- [ x] I have read all of the [`README`](https://github.com/jessesquires/DefaultStringConvertible/blob/develop/README.md) and [documentation](http://www.jessesquires.com/DefaultStringConvertible/).
- [ x] I have reviewed the [contributing guidelines](https://github.com/jessesquires/HowToContribute).
- [x ] I have searched [existing issues](https://github.com/jessesquires/DefaultStringConvertible/issues?q=is%3Aissue+sort%3Acreated-desc) and **this is not a duplicate**.
## General information
- Library version(s): 1.1.0
- OS version(s): OS X 11.6 
- Devices/Simulators affected: NA
- Reproducible in the demo project (Yes/No): NA
- Related issues:
## Expected behavior

> Success on Carthage update
## Actual behavior

> Carthage update fail
## Steps to reproduce

> On terminal:
> `$ carthage update --platform iOS`
### Crash log? Screenshots? Videos? Sample project?

> ```
> Building scheme "DefaultStringConvertible-iOS" in DefaultStringConvertible.xcodeproj
> The following build commands failed:
>     Check dependencies
> (1 failure)
> A shell task (/usr/bin/xcrun xcodebuild -project somePath/Carthage/Checkouts/DefaultStringConvertible/DefaultStringConvertible.xcodeproj -scheme DefaultStringConvertible-iOS -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
> ```

**Comment by jessesquires** [comment]
Thanks @Domsware !

Just tested this with release `2.0` and everything seems to be working now.

**Comment by ghost** [comment]
Thanks Jesse,

Everything is fine now.
