### ISSUE TITLE
travis is broken

### ISSUE THREAD

**Issue by jessesquires** [jessesquires/DefaultStringConvertible#5]
Looks like format/syntax of `.travis.yml` has changed. `lint` now fails.

https://travis-ci.org/jessesquires/DefaultStringConvertible/builds/171262111

**Comment by jessesquires** [comment]
cc @broadwaylamb

**Comment by jessesquires** [comment]
we almost had everything good, here:

https://travis-ci.org/jessesquires/DefaultStringConvertible/builds/171143213

the problem is that travis has an old version of cocoapods (which is why `pod lint` fails), so we need to update cocoapods before linting

**Comment by broadwaylamb** [comment]
@jessesquires I'll take a look at it.
