### ISSUE TITLE
deepUnwrap broken for Swift 3

### ISSUE THREAD

**Issue by edmw** [jessesquires/DefaultStringConvertible#7]
Hi,
Mirror.Child.label for Optionals has changed from "Some" to "some" in Swift 3.

https://github.com/jessesquires/DefaultStringConvertible/blob/develop/Sources/DefaultStringConvertible.swift#L91

## Expected behavior

deepUnwrap should return unwrapped Optional.

## Actual behavior

deepUnwrap returns nil unconditionally.

**Comment by jessesquires** [comment]
Thanks @edmw ! 👍 

cc @broadwaylamb
